# Generated by Django 4.0.5 on 2022-07-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_address_doctor_profile_pic_doctor_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
