# Generated by Django 4.0.5 on 2022-07-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_doctor_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
