# Generated by Django 4.0.5 on 2022-07-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_labtest_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Patientappointment',
        ),
    ]
