# Generated by Django 4.0.5 on 2022-07-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_appointment_patientappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='time',
            field=models.CharField(choices=[('09:00 - 10:00', '09:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00'), ('13:00 - 14:00', '13:00 - 14:00')], max_length=50, null=True),
        ),
    ]
