# Generated by Django 4.0.5 on 2022-07-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_labtest_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='date_of_birth',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
