# Generated by Django 4.0.5 on 2022-07-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_patientappointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='time',
            field=models.CharField(choices=[('1', '09:00 - 10:00'), ('2', '10:00 - 11:00'), ('3', '11:00 - 12:00'), ('4', '2:00 - 3:00'), ('5', '3:00 - 4:00')], max_length=50, null=True),
        ),
    ]
