# Generated by Django 4.0.5 on 2022-07-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_labtest_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='date',
            field=models.DateField(),
        ),
    ]
