# Generated by Django 4.0.5 on 2022-07-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_patientappointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
