# Generated by Django 4.0.5 on 2023-11-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_labtest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='core.doctor'),
        ),
    ]
